[tool.poetry]
name = "rag-backend"
version = "0.1.0"
description = "Backend para RAG con FastAPI y Langchain"
authors = ["Tu Nombre <tu@email.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "*"
uvicorn = "*"
langchain = "*"
langchain-community = "*"
langchain-qdrant = "*"
langchain-ollama = "*"
langchain-openai = "*"
langchain-google-genai = "*"
pypdf = "*"
python-multipart = "*"
qdrant-client = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
